/**
 * Sample events data for demonstration purposes
 */
const eventsData = [
    {
      id: 1,
      eventName: "Community Food Drive",
      name: "Community Food Drive",
      location: "Central Community Center, 123 Main St",
      eventDate: "2025-02-15T09:00:00Z",
      date: "2025-02-15T09:00:00Z",
      startTime: "09:00 AM",
      time: "09:00 AM",
      endTime: "03:00 PM",
      eventDescription: "Help collect and distribute food packages to community members in need. We need volunteers to sort donations, pack food boxes, and assist with distribution.",
      description: "Help collect and distribute food packages to community members in need. We need volunteers to sort donations, pack food boxes, and assist with distribution.",
      maxVolunteers: 20,
      volunteersNeeded: 20,
      volunteersAssigned: 5,
      volunteersRegistered: 5,
      requiredSkills: ["organizing", "heavy lifting", "customer service"],
      skills: ["organizing", "heavy lifting", "customer service"],
      urgency: "High",
      contactPerson: "Maria Rodriguez",
      contactEmail: "maria.r@impactnow.org",
      contactPhone: "555-789-1234",
      status: "Active",
      visibility: "Public",
      createdAt: "2025-01-05T10:00:00Z",
      createdBy: "admin"
    },
    {
      id: 2,
      eventName: "Tech Workshop for Seniors",
      name: "Tech Workshop for Seniors",
      location: "Downtown Library, 456 Oak Avenue",
      eventDate: "2025-02-20T13:00:00Z",
      date: "2025-02-20T13:00:00Z",
      startTime: "1:00 PM",
      time: "1:00 PM",
      endTime: "4:00 PM",
      eventDescription: "Teach basic computer and smartphone skills to senior citizens. Volunteers will work one-on-one with seniors to help them learn how to use technology for everyday tasks.",
      description: "Teach basic computer and smartphone skills to senior citizens. Volunteers will work one-on-one with seniors to help them learn how to use technology for everyday tasks.",
      maxVolunteers: 10,
      volunteersNeeded: 10,
      volunteersAssigned: 2,
      volunteersRegistered: 2,
      requiredSkills: ["teaching", "patience", "computer skills"],
      skills: ["teaching", "patience", "computer skills"],
      urgency: "Medium",
      contactPerson: "James Wilson",
      contactEmail: "james.w@impactnow.org",
      contactPhone: "555-456-7890",
      status: "Active",
      visibility: "Public",
      createdAt: "2025-01-10T14:30:00Z",
      createdBy: "admin"
    },
    {
      id: 3,
      eventName: "Park Cleanup",
      name: "Park Cleanup",
      location: "Riverside Park, River Road",
      eventDate: "2025-01-18T08:00:00Z",
      date: "2025-01-18T08:00:00Z",
      startTime: "8:00 AM",
      time: "8:00 AM",
      endTime: "12:00 PM",
      eventDescription: "Help clean up our community park! We'll be picking up trash, planting trees, and making minor repairs to park equipment. All cleaning supplies will be provided.",
      description: "Help clean up our community park! We'll be picking up trash, planting trees, and making minor repairs to park equipment. All cleaning supplies will be provided.",
      maxVolunteers: 30,
      volunteersNeeded: 30,
      volunteersAssigned: 15,
      volunteersRegistered: 15,
      requiredSkills: ["outdoor work", "gardening", "physical activity"],
      skills: ["outdoor work", "gardening", "physical activity"],
      urgency: "Medium",
      contactPerson: "Robert Chen",
      contactEmail: "robert.c@impactnow.org",
      contactPhone: "555-222-3333",
      status: "Completed",
      visibility: "Public",
      createdAt: "2025-01-02T09:15:00Z",
      createdBy: "admin"
    },
    {
      id: 4,
      eventName: "Health Fair",
      name: "Health Fair",
      location: "Community Hospital, 789 Health Blvd",
      eventDate: "2025-01-25T10:00:00Z",
      date: "2025-01-25T10:00:00Z",
      startTime: "10:00 AM",
      time: "10:00 AM",
      endTime: "4:00 PM",
      eventDescription: "Annual health fair providing free screenings and health information to community members. Volunteers will help with check-in, guide attendees, and assist healthcare professionals.",
      description: "Annual health fair providing free screenings and health information to community members. Volunteers will help with check-in, guide attendees, and assist healthcare professionals.",
      maxVolunteers: 15,
      volunteersNeeded: 15,
      volunteersAssigned: 8,
      volunteersRegistered: 8,
      requiredSkills: ["customer service", "organization", "healthcare knowledge"],
      skills: ["customer service", "organization", "healthcare knowledge"],
      urgency: "Medium",
      contactPerson: "Sarah Johnson",
      contactEmail: "sarah.j@impactnow.org",
      contactPhone: "555-111-2222",
      status: "Completed",
      visibility: "Public",
      createdAt: "2025-01-03T11:45:00Z",
      createdBy: "admin"
    },
    {
      id: 5,
      eventName: "Children's Reading Hour",
      name: "Children's Reading Hour",
      location: "Public Library, 222 Book Lane",
      eventDate: "2025-02-10T15:00:00Z",
      date: "2025-02-10T15:00:00Z",
      startTime: "3:00 PM",
      time: "3:00 PM",
      endTime: "5:00 PM",
      eventDescription: "Read stories to children ages 5-10 at the community library. Volunteers will take turns reading children's books and lead simple activities related to the stories.",
      description: "Read stories to children ages 5-10 at the community library. Volunteers will take turns reading children's books and lead simple activities related to the stories.",
      maxVolunteers: 5,
      volunteersNeeded: 5,
      volunteersAssigned: 3,
      volunteersRegistered: 3,
      requiredSkills: ["reading", "working with children", "creativity"],
      skills: ["reading", "working with children", "creativity"],
      urgency: "Low",
      contactPerson: "Emily Parker",
      contactEmail: "emily.p@impactnow.org",
      contactPhone: "555-777-8888",
      status: "Active",
      visibility: "Public",
      createdAt: "2025-01-20T13:00:00Z",
      createdBy: "admin"
    },
    {
      id: 6,
      eventName: "Community Dinner",
      name: "Community Dinner",
      location: "Hope Shelter, 333 Hope Street",
      eventDate: "2025-02-05T17:00:00Z",
      date: "2025-02-05T17:00:00Z",
      startTime: "5:00 PM",
      time: "5:00 PM",
      endTime: "8:00 PM",
      eventDescription: "Prepare and serve dinner for community members experiencing food insecurity. Volunteers will help with meal preparation, serving, and cleanup.",
      description: "Prepare and serve dinner for community members experiencing food insecurity. Volunteers will help with meal preparation, serving, and cleanup.",
      maxVolunteers: 12,
      volunteersNeeded: 12,
      volunteersAssigned: 10,
      volunteersRegistered: 10,
      requiredSkills: ["cooking", "food service", "teamwork"],
      skills: ["cooking", "food service", "teamwork"],
      urgency: "Medium",
      contactPerson: "David Martinez",
      contactEmail: "david.m@impactnow.org",
      contactPhone: "555-333-4444",
      status: "Active",
      visibility: "Public",
      createdAt: "2025-01-15T16:30:00Z",
      createdBy: "admin"
    },
    {
      id: 7,
      eventName: "Fundraising Gala",
      name: "Fundraising Gala",
      location: "Grand Hotel, 555 Luxury Ave",
      eventDate: "2025-03-10T18:00:00Z",
      date: "2025-03-10T18:00:00Z",
      startTime: "6:00 PM",
      time: "6:00 PM",
      endTime: "10:00 PM",
      eventDescription: "Annual fundraising event to support our organization's programs. Volunteers will help with setup, greeting guests, silent auction management, and cleanup.",
      description: "Annual fundraising event to support our organization's programs. Volunteers will help with setup, greeting guests, silent auction management, and cleanup.",
      maxVolunteers: 15,
      volunteersNeeded: 15,
      volunteersAssigned: 0,
      volunteersRegistered: 0,
      requiredSkills: ["customer service", "event planning", "attention to detail"],
      skills: ["customer service", "event planning", "attention to detail"],
      urgency: "High",
      contactPerson: "Nancy Williams",
      contactEmail: "nancy.w@impactnow.org",
      contactPhone: "555-666-7777",
      status: "Active",
      visibility: "Public",
      createdAt: "2025-01-30T09:00:00Z",
      createdBy: "admin"
    },
    {
      id: 8,
      eventName: "Spring Charity Run",
      name: "Spring Charity Run",
      location: "City Park, Park Avenue",
      eventDate: "2025-04-15T07:00:00Z",
      date: "2025-04-15T07:00:00Z",
      startTime: "7:00 AM",
      time: "7:00 AM",
      endTime: "12:00 PM",
      eventDescription: "5K charity run to raise funds for local education programs. Volunteers needed for registration, water stations, course marshals, and post-race activities.",
      description: "5K charity run to raise funds for local education programs. Volunteers needed for registration, water stations, course marshals, and post-race activities.",
      maxVolunteers: 30,
      volunteersNeeded: 30,
      volunteersAssigned: 0,
      volunteersRegistered: 0,
      requiredSkills: ["organization", "customer service", "physical activity"],
      skills: ["organization", "customer service", "physical activity"],
      urgency: "Medium",
      contactPerson: "Thomas Brown",
      contactEmail: "thomas.b@impactnow.org",
      contactPhone: "555-444-3333",
      status: "Planning",
      visibility: "Public",
      createdAt: "2025-02-01T10:15:00Z",
      createdBy: "admin"
    },
    {
      id: 9,
      eventName: "Community Garden Project",
      name: "Community Garden Project",
      location: "Urban Gardens, 777 Green Street",
      eventDate: "2025-03-05T09:00:00Z",
      date: "2025-03-05T09:00:00Z",
      startTime: "9:00 AM",
      time: "9:00 AM",
      endTime: "2:00 PM",
      eventDescription: "Help prepare community garden beds for spring planting. Volunteers will clear debris, prepare soil, build garden boxes, and plant seeds.",
      description: "Help prepare community garden beds for spring planting. Volunteers will clear debris, prepare soil, build garden boxes, and plant seeds.",
      maxVolunteers: 20,
      volunteersNeeded: 20,
      volunteersAssigned: 0,
      volunteersRegistered: 0,
      requiredSkills: ["gardening", "physical activity", "outdoor work"],
      skills: ["gardening", "physical activity", "outdoor work"],
      urgency: "Medium",
      contactPerson: "Lisa Green",
      contactEmail: "lisa.g@impactnow.org",
      contactPhone: "555-222-1111",
      status: "Active",
      visibility: "Public",
      createdAt: "2025-01-25T14:30:00Z",
      createdBy: "admin"
    },
    {
      id: 10,
      eventName: "After-School Tutoring",
      name: "After-School Tutoring",
      location: "Lincoln Middle School, 888 Education Blvd",
      eventDate: "2025-02-12T15:00:00Z",
      date: "2025-02-12T15:00:00Z",
      startTime: "3:00 PM",
      time: "3:00 PM",
      endTime: "5:00 PM",
      eventDescription: "Provide academic support to middle school students in math, science, and language arts. Volunteers will work with small groups or individual students.",
      description: "Provide academic support to middle school students in math, science, and language arts. Volunteers will work with small groups or individual students.",
      maxVolunteers: 10,
      volunteersNeeded: 10,
      volunteersAssigned: 7,
      volunteersRegistered: 7,
      requiredSkills: ["teaching", "patience", "subject knowledge"],
      skills: ["teaching", "patience", "subject knowledge"],
      urgency: "Medium",
      contactPerson: "Michael Taylor",
      contactEmail: "michael.t@impactnow.org",
      contactPhone: "555-999-8888",
      status: "Active",
      visibility: "Public",
      createdAt: "2025-01-10T15:45:00Z",
      createdBy: "admin"
    }
  ];
  
  module.exports = eventsData;