/**
 * Sample volunteer data for demonstration purposes
 */
const volunteersData = [
    {
      id: 1,
      username: "jdoe",
      first_name: "John",
      last_name: "Doe",
      email: "john.doe@example.com",
      phone_number: "(555) 123-4567",
      location: "New York, NY",
      role: "General Volunteer",
      skills: ["teaching", "organizing", "first aid"],
      availability: ["weekends", "evenings"],
      active: true
    },
    {
      id: 2,
      username: "jsmith",
      first_name: "Jane",
      last_name: "Smith",
      email: "jane.smith@example.com",
      phone_number: "(555) 987-6543",
      location: "Los Angeles, CA",
      role: "Team Leader",
      skills: ["leadership", "communication", "event planning"],
      availability: ["weekdays", "afternoons"],
      active: true
    },
    {
      id: 3,
      username: "mjohnson",
      first_name: "Michael",
      last_name: "Johnson",
      email: "michael.j@example.com",
      phone_number: "(555) 345-6789",
      location: "Chicago, IL",
      role: "Technical Support",
      skills: ["IT", "audio/visual", "photography"],
      availability: ["weekends"],
      active: true
    },
    {
      id: 4,
      username: "lwilliams",
      first_name: "Laura",
      last_name: "Williams",
      email: "laura.w@example.com",
      phone_number: "(555) 456-7890",
      location: "Houston, TX",
      role: "Medical Volunteer",
      skills: ["nursing", "first aid", "CPR certified"],
      availability: ["weekends", "evenings", "mornings"],
      active: true
    },
    {
      id: 5,
      username: "rbrown",
      first_name: "Robert",
      last_name: "Brown",
      email: "robert.b@example.com",
      phone_number: "(555) 234-5678",
      location: "Philadelphia, PA",
      role: "General Volunteer",
      skills: ["driving", "heavy lifting", "cooking"],
      availability: ["weekends"],
      active: true
    },
    {
      id: 6,
      username: "ewilson",
      first_name: "Emily",
      last_name: "Wilson",
      email: "emily.w@example.com",
      phone_number: "(555) 876-5432",
      location: "Phoenix, AZ",
      role: "Youth Coordinator",
      skills: ["teaching", "child care", "art and craft"],
      availability: ["afternoons", "weekends"],
      active: true
    },
    {
      id: 7,
      username: "dthomas",
      first_name: "David",
      last_name: "Thomas",
      email: "david.t@example.com",
      phone_number: "(555) 765-4321",
      location: "San Antonio, TX",
      role: "Food Service",
      skills: ["cooking", "food handling", "inventory management"],
      availability: ["mornings", "evenings"],
      active: true
    },
    {
      id: 8,
      username: "jlee",
      first_name: "Jennifer",
      last_name: "Lee",
      email: "jennifer.l@example.com",
      phone_number: "(555) 654-3210",
      location: "San Diego, CA",
      role: "Administrative Support",
      skills: ["data entry", "organization", "communication"],
      availability: ["weekdays"],
      active: true
    },
    {
      id: 9,
      username: "pgarcia",
      first_name: "Patricia",
      last_name: "Garcia",
      email: "patricia.g@example.com",
      phone_number: "(555) 321-0987",
      location: "Dallas, TX",
      role: "Translator",
      skills: ["Spanish", "Portuguese", "interpretation"],
      availability: ["weekends", "evenings"],
      active: true
    },
    {
      id: 10,
      username: "jmartinez",
      first_name: "Jose",
      last_name: "Martinez",
      email: "jose.m@example.com",
      phone_number: "(555) 210-9876",
      location: "San Jose, CA",
      role: "Driver",
      skills: ["driving", "navigation", "vehicle maintenance"],
      availability: ["weekends", "evenings"],
      active: true
    },
    {
      id: 11,
      username: "krobinson",
      first_name: "Karen",
      last_name: "Robinson",
      email: "karen.r@example.com",
      phone_number: "(555) 109-8765",
      location: "Austin, TX",
      role: "Fundraising",
      skills: ["sales", "networking", "public speaking"],
      availability: ["weekdays", "evenings"],
      active: true
    },
    {
      id: 12,
      username: "dclark",
      first_name: "Daniel",
      last_name: "Clark",
      email: "daniel.c@example.com",
      phone_number: "(555) 098-7654",
      location: "Jacksonville, FL",
      role: "General Volunteer",
      skills: ["manual labor", "organization", "cleaning"],
      availability: ["weekends"],
      active: true
    },
    {
      id: 13,
      username: "lrodriguez",
      first_name: "Linda",
      last_name: "Rodriguez",
      email: "linda.r@example.com",
      phone_number: "(555) 987-0123",
      location: "Indianapolis, IN",
      role: "Event Coordinator",
      skills: ["event planning", "organization", "leadership"],
      availability: ["weekdays", "weekends"],
      active: true
    },
    {
      id: 14,
      username: "mlewis",
      first_name: "Mary",
      last_name: "Lewis",
      email: "mary.l@example.com",
      phone_number: "(555) 876-0123",
      location: "Columbus, OH",
      role: "General Volunteer",
      skills: ["teaching", "tutoring", "mentoring"],
      availability: ["afternoons", "weekends"],
      active: true
    },
    {
      id: 15,
      username: "jwalker",
      first_name: "James",
      last_name: "Walker",
      email: "james.w@example.com",
      phone_number: "(555) 765-0123",
      location: "Charlotte, NC",
      role: "Technical Support",
      skills: ["IT", "computer repair", "networking"],
      availability: ["evenings", "weekends"],
      active: true
    }
  ];
  
  module.exports = volunteersData;